"""
Django settings for Portfolio project.

Generated by 'django-admin startproject' using Django 2.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from . import settings
import dj_database_url
import os

settings.DEBUG = True
settings.TEMPLATE_DEBUG = True

# ToDo: Finish setting up Heroku Allowed Hosts for Dev
# ALLOWED_HOSTS = [
#     '127.0.0.1', 'localhost', 'portdev.herokuapp.com'
# ]
settings.ALLOWED_HOSTS = ['*']
# Use the production secret key
settings.SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# Security settings https://docs.djangoproject.com/en/3.2/topics/security/
# SSL/HTTPS
settings.SECURE_SSL_REDIRECT = True
settings.SESSION_COOKIE_SECURE = True
settings.CSRF_COOKIE_SECURE = True

settings.DATABASE_URL = os.environ['DATABASE_URL']

settings.DATABASES = {'default': dj_database_url.config(
    default=settings.DATABASE_URL)}
