# Generated by Django 3.2.12 on 2022-03-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('copy', markdownx.models.MarkdownxField(max_length=3000)),
                ('short_summary', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=500)),
                ('professional_development', models.BooleanField(default=False)),
                ('field_experience', models.BooleanField(default=False)),
                ('github_link', models.CharField(max_length=250)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=180)),
                ('organization', models.CharField(max_length=180)),
                ('summary', models.TextField(max_length=1000)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('copy', markdownx.models.MarkdownxField(max_length=3000)),
                ('summary', models.CharField(max_length=250)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_summary', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=500)),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.workexperience')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_of_study', models.CharField(max_length=180)),
                ('degree', models.CharField(max_length=180)),
                ('institution', models.CharField(max_length=180)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume')),
            ],
        ),
        migrations.CreateModel(
            name='CourseWork',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('short_summary', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=500)),
                ('copy', markdownx.models.MarkdownxField(max_length=3000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.education'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('short_summary', models.CharField(max_length=250)),
                ('summary', models.TextField(max_length=500)),
                ('copy', markdownx.models.MarkdownxField(max_length=3000)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.education')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.project')),
            ],
        ),
    ]
