# Generated by Django 2.2.6 on 2019-11-08 12:06

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('completion', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('po_box', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('expired', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=30)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('accomplishment', models.ManyToManyField(blank=True, to='portfolio.Accomplishment', verbose_name='accomplishments')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('shortend_md', markdownx.models.MarkdownxField(blank=True)),
                ('mark_down', markdownx.models.MarkdownxField(blank=True)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('related_skill', models.ManyToManyField(blank=True, to='portfolio.Skill', verbose_name='related skill')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, upload_to='')),
                ('expired', models.BooleanField()),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('certificates', models.ManyToManyField(blank=True, to='portfolio.Certificate', verbose_name='Certificates')),
                ('education', models.ManyToManyField(blank=True, to='portfolio.School', verbose_name='Education History')),
                ('job', models.ManyToManyField(blank=True, to='portfolio.Job', verbose_name='Job History')),
                ('section', models.ManyToManyField(blank=True, to='portfolio.Section', verbose_name='Extra Sections')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
                ('related_skill', models.ManyToManyField(blank=True, to='portfolio.Skill', verbose_name='related skill')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('highlights', markdownx.models.MarkdownxField(blank=True)),
                ('code_snippets', models.ManyToManyField(blank=True, to='portfolio.CodeSnippet', verbose_name='Project Code Snippets')),
                ('files', models.ManyToManyField(blank=True, to='portfolio.File', verbose_name='Project Files')),
                ('mark_down_sections', models.ManyToManyField(blank=True, to='portfolio.ProjectSection', verbose_name='Project Description Sections')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='responsibility',
            field=models.ManyToManyField(blank=True, to='portfolio.Responsibility', verbose_name='responsibilities'),
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mark_down', markdownx.models.MarkdownxField(blank=True)),
                ('date', models.DateField()),
                ('accomplishment', models.ManyToManyField(blank=True, to='portfolio.Accomplishment', verbose_name='Accomplishments')),
                ('certificates', models.ManyToManyField(blank=True, to='portfolio.Certificate', verbose_name='Certificates')),
                ('education', models.ManyToManyField(blank=True, to='portfolio.School', verbose_name='Education History')),
                ('job', models.ManyToManyField(blank=True, to='portfolio.Job', verbose_name='Job History')),
                ('projects', models.ManyToManyField(blank=True, to='portfolio.Project', verbose_name='Projects')),
                ('section', models.ManyToManyField(blank=True, to='portfolio.Section', verbose_name='Extra Sections')),
                ('skills', models.ManyToManyField(blank=True, to='portfolio.Skill', verbose_name='Skills')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='related_skill',
            field=models.ManyToManyField(blank=True, to='portfolio.Skill', verbose_name='related skill'),
        ),
        migrations.AddField(
            model_name='accomplishment',
            name='related_skill',
            field=models.ManyToManyField(blank=True, to='portfolio.Skill', verbose_name='related skill'),
        ),
    ]
