# Generated by Django 3.2.12 on 2022-03-18 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20220318_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume'),
        ),
    ]
