# Generated by Django 3.2.12 on 2022-03-18 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220318_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='end',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 1, 22, 33, 850154)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 1, 22, 46, 398511)),
            preserve_default=False,
        ),
    ]
