# Generated by Django 2.2.6 on 2020-09-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='highlights',
            new_name='short_desc',
        ),
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
