# Generated by Django 3.2.12 on 2022-03-18 11:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20220318_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 11, 33, 43, 240923)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='end',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 11, 33, 51, 815688)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='start',
            field=models.DateField(default=datetime.datetime(2022, 3, 18, 11, 33, 55, 431837)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.education'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.project'),
        ),
    ]
