# Generated by Django 3.2.12 on 2022-03-18 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220318_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
