# Generated by Django 3.2.12 on 2022-03-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_project_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='copy',
        ),
        migrations.AddField(
            model_name='achievement',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.workexperience'),
        ),
    ]
