# Generated by Django 3.2.12 on 2022-03-20 20:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20220320_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 20, 55, 18, 865592, tzinfo=utc)),
        ),
    ]
