# Generated by Django 3.2.12 on 2022-03-20 22:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_responsibility_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.curriculumvitae'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 20, 22, 5, 45, 895184, tzinfo=utc)),
        ),
    ]
