# Generated by Django 3.2.12 on 2022-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20220209_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
