# Generated by Django 3.2.12 on 2022-03-22 11:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20220322_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 11, 58, 42, 374796, tzinfo=utc)),
        ),
    ]
