# Generated by Django 3.2.12 on 2022-03-22 12:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20220322_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 22, 12, 4, 12, 967532, tzinfo=utc)),
        ),
    ]
