# Generated by Django 3.2.12 on 2022-03-23 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_responsibility_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 23, 12, 20, 44, 425787, tzinfo=utc)),
        ),
    ]
