# Generated by Django 3.2.12 on 2022-03-25 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_responsibility_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='project',
        ),
        migrations.AddField(
            model_name='achievement',
            name='course_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.coursework'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=datetime.datetime(2022, 3, 25, 0, 7, 50, 553346, tzinfo=utc)),
        ),
    ]
