# Generated by Django 3.2.12 on 2022-03-25 01:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20220325_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
