# Generated by Django 3.2.12 on 2022-03-30 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_responsibility_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
