# Generated by Django 3.2.12 on 2022-03-15 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import secured_fields.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=250)),
                ('phone', secured_fields.fields.EncryptedCharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkedIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='Keybase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='HackTheBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='GitHub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='Codewars',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='CodePen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=250)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession', models.CharField(max_length=250)),
                ('copy', markdownx.models.MarkdownxField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street_one', secured_fields.fields.EncryptedCharField(max_length=250)),
                ('street_two', secured_fields.fields.EncryptedCharField(max_length=250)),
                ('city', secured_fields.fields.EncryptedCharField(max_length=180)),
                ('state', secured_fields.fields.EncryptedCharField(max_length=180)),
                ('zip', secured_fields.fields.EncryptedCharField(max_length=10)),
                ('contact_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard', unique=True)),
            ],
        ),
    ]
