# Generated by Django 3.2.12 on 2022-03-15 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acct_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acct_management.contactcard'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
