# Generated by Django 3.2.12 on 2022-03-23 12:20

from django.db import migrations, models
import secured_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('acct_management', '0002_auto_20220315_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_two',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='phone',
            field=secured_fields.fields.EncryptedCharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contactcard',
            name='website',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
