# Generated by Django 2.2.6 on 2019-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitae',
            name='skills',
            field=models.ManyToManyField(blank=True, to='RossDevs.Skill', verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='bio',
            name='expired',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='curriculumvitae',
            name='accomplishment',
            field=models.ManyToManyField(blank=True, to='RossDevs.Accomplishment', verbose_name='Accomplishments'),
        ),
    ]
