# Generated by Django 2.2.6 on 2019-11-08 12:09

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('mark_down', markdownx.models.MarkdownxField(blank=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField()),
            ],
        ),
    ]
