# Generated by Django 2.2.6 on 2019-11-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0002_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactcard',
            name='expired',
        ),
    ]
