# Generated by Django 2.2.6 on 2019-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('RossDevs', '0002_curriculumvitae_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitae',
            name='accomplishment',
            field=models.ManyToManyField(blank=True, to='RossDevs.Accomplishment', verbose_name='Accomplishments'),
        ),
    ]
