# Generated by Django 2.2.6 on 2019-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('RossDevs', '0003_auto_20191105_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='expired',
            field=models.BooleanField(),
        ),
    ]
