# Generated by Django 2.2.6 on 2019-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0003_remove_contactcard_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactcard',
            name='expired',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
