# Generated by Django 2.2.6 on 2019-11-12 01:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0004_contactcard_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='mark_down',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsection',
            name='mark_down',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
