# Generated by Django 2.2.6 on 2021-03-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0009_auto_20210321_0029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievment',
            new_name='Achievement',
        ),
    ]
