# Generated by Django 2.2.6 on 2021-03-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RossDevs', '0010_auto_20210321_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='desciprion',
            new_name='description',
        ),
    ]
